# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bazooka < Formula
  desc ""
  homepage "https://github.com/aosasona/homebrew-bazooka"
  version "0.1.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.16/bazooka_0.1.16_Darwin_arm64.tar.gz"
      sha256 "71b1410b20f1ac7ef6e27a0c461abbeeaed7c9b669f53e10988a15fef2df9b1a"

      def install
        bin.install "bazooka"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.16/bazooka_0.1.16_Darwin_x86_64.tar.gz"
      sha256 "2a45b3ad5d7861ea2d41a4fc9d860abb69c3109e352ff2b502abaec86109d091"

      def install
        bin.install "bazooka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.16/bazooka_0.1.16_Linux_arm64.tar.gz"
      sha256 "9a667438a63d2e9b63b2cfbd551a99d239880917a0925ff6ef7399e38b60cc87"

      def install
        bin.install "bazooka"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.16/bazooka_0.1.16_Linux_x86_64.tar.gz"
      sha256 "6928bfdcb0a26c1a2742ed5ab05995e1c1391411f995d9021134bb245c24bd0a"

      def install
        bin.install "bazooka"
      end
    end
  end
end
