# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bazooka < Formula
  desc ""
  homepage "https://github.com/aosasona/homebrew-bazooka"
  version "0.1.20"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.20/bazooka_0.1.20_Darwin_arm64.tar.gz"
      sha256 "85ea335c20919b5de60f13e1d402f331fd978321df9a4341fa8b07f0539e268c"

      def install
        bin.install "bazooka"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.20/bazooka_0.1.20_Darwin_x86_64.tar.gz"
      sha256 "5880887e05782861a60871efcf92bf1535e62e0f66a60d4511a40c2fed798c1d"

      def install
        bin.install "bazooka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.20/bazooka_0.1.20_Linux_arm64.tar.gz"
      sha256 "0d92e2822133b65384ec34f6318cd012921336d1d78e76ad8e1caa5752d0f5df"

      def install
        bin.install "bazooka"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.20/bazooka_0.1.20_Linux_x86_64.tar.gz"
      sha256 "5901bb20799460e1cb00891c8b64e5413b707afdd502a5b937bf92a056bf3457"

      def install
        bin.install "bazooka"
      end
    end
  end
end
