# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bazooka < Formula
  desc ""
  homepage "https://github.com/aosasona/homebrew-bazooka"
  version "0.1.22"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.22/bazooka_0.1.22_Darwin_arm64.tar.gz"
      sha256 "32fb24e408a7d277a53b82c95efc99cbef55d2f476c710f595f19f296ceb8792"

      def install
        bin.install "bazooka"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.22/bazooka_0.1.22_Darwin_x86_64.tar.gz"
      sha256 "721c3dd41a44d5787b7cce4dd7a0589e9bddb688ab98b9a66837d0d2e1a10be5"

      def install
        bin.install "bazooka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.22/bazooka_0.1.22_Linux_arm64.tar.gz"
      sha256 "f0ef0b22c8179ee031df99f28100bef06c7a4500460cfee8afaa96e59e37f01d"

      def install
        bin.install "bazooka"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/bazooka/releases/download/v0.1.22/bazooka_0.1.22_Linux_x86_64.tar.gz"
      sha256 "6d5bc016ae6ecb2d5007e4316d8c97725d6252735f05e2f9a23f633918432c0a"

      def install
        bin.install "bazooka"
      end
    end
  end
end
